#!/bin/bash

CONTAINER_POLICY_ID=$(uuidgen --namespace '@dns' --name "$K8S_POD_NAMESPACE/$K8S_POD_NAME")

STDIN=$(sed 's#{#{"metadata":{"policy_group_id":"'$CONTAINER_POLICY_ID'","app_id":"'$CNI_CONTAINERID'"},#')
echo "$STDIN" | /var/vcap/packages/silk-cni/bin/cni-wrapper-plugin <&0 2>&1 | tee -a /tmp/cni-wrapper-plugin-out.log

