#!/bin/bash



while curl localhost:23954; do
 if [ $? -eq 0 ]; then
   SILK_CIDR=$(curl -s localhost:23954 | cut -f4 -d'"')
   break;
 else
   sleep 1;
 fi

done
SERVICE_NETWORK_CIDR="10.100.0.0/16"
# ALLOW ALL TRAFFIC ON KUBE MASTER
MASTER_HOSTNAMES=<% if_link("kube-apiserver") do |instances| instances.instances.map do |instance|%><%= instance.address %>,<% end end %>
# ALLOW ALL TRAFFIC ON KUBE MASTER
WORKER_HOSTNAMES=<% if_link("kubernetes-workers") do |instances| instances.instances.map do |instance|%><%= instance.address %>,<% end end %>
SELF_HOSTNAME="<%= spec.address %>"
WORKER_HOSTNAMES=${WORKER_HOSTNAMES:-1}
MASTER_HOSTNAMES=${MASTER_HOSTNAMES:-1}


# ONLY USING INSERT, FIRST RULES ADDED WILL BE LAST ONES TO TRAVERSE, THUS EVERYTHING GETS LOGGED THAT DID NOT HIT ANOTHER CHAIN

IFS=','; for HOST in ${MASTER_HOSTNAMES[@]}; do
  iptables -t filter -I FORWARD -s "$SILK_CIDR" -d "$HOST" -o eth0 -j ACCEPT
done
iptables -t filter -I FORWARD -s "$SILK_CIDR" ! -d "10.255.0.0/16" -j ACCEPT
iptables -t filter -I FORWARD -s "$SILK_CIDR" -d "$SILK_CIDR" -j ACCEPT
iptables -t filter -I OUTPUT -s "$SILK_CIDR" ! -d "10.255.0.0/16" -j ACCEPT
iptables -t filter -I INPUT -s "$SILK_CIDR" -d "$SELF_HOSTNAME" -j ACCEPT


exit 0
iptables -t raw -I PREROUTING -j TRACE
iptables -t raw -I OUTPUT -j TRACE


iptables -t mangle -I POSTROUTING -s 169.254.0.1 -d "$SILK_CIDR" -j ACCEPT
iptables -t filter -I INPUT -s "$SILK_CIDR" -d "$SELF_HOSTNAME" -j ACCEPT


IFS=','; for HOST in ${MASTER_HOSTNAMES[@]}; do
  iptables -t filter -I FORWARD -s "$SILK_CIDR" -d "$HOST" -o eth0 -j ACCEPT
done 
iptables -t filter -I FORWARD -s "$SILK_CIDR" -o eth0 -j ACCEPT
iptables -t filter -I FORWARD -s "$SILK_CIDR" -d "$SILK_CIDR" -j ACCEPT




# OUTPUT & FORWARD POLICY ACCEPT ON filter,nat,mangle

iptables -t filter -P OUTPUT ACCEPT
iptables -t filter -P FORWARD ACCEPT
iptables -t nat -P FORWARD ACCEPT
iptables -t nat -P OUTPUT ACCEPT
iptables -t mangle -P FORWARD ACCEPT
iptables -t mangle -P OUTPUT ACCEPT

# OUTPUT eth0 ACCEPT
iptables -I OUTPUT -o eth0 -j ACCEPT
iptables -t nat -I OUTPUT -o eth0 -j ACCEPT
iptables -t security -I OUTPUT -o eth0 -j ACCEPT
iptables -t raw -I OUTPUT -o eth0 -j ACCEPT
iptables -t filter -I OUTPUT -o eth0 -j ACCEPT
# INPUT lo ACCEPT
iptables -I INPUT -i lo -j ACCEPT
iptables -t security -I INPUT -i lo -j ACCEPT
iptables -t filter -I INPUT -i lo -j ACCEPT
# OUTPUT lo ACCEPT
iptables -I OUTPUT -o lo -j ACCEPT
iptables -t nat -I OUTPUT -o lo -j ACCEPT
iptables -t security -I OUTPUT -o lo -j ACCEPT
iptables -t raw -I OUTPUT -o lo -j ACCEPT
iptables -t filter -I OUTPUT -o lo -j ACCEPT

# OUTPUT silk-vtep ACCEPT
iptables -I OUTPUT -o silk-vtep -j ACCEPT
iptables -t nat -I OUTPUT -o silk-vtep -j ACCEPT
iptables -t security -I OUTPUT -o silk-vtep -j ACCEPT
iptables -t raw -I OUTPUT -o silk-vtep -j ACCEPT
iptables -t filter -I OUTPUT -o silk-vtep -j ACCEPT
